export const hairColors = [
  'Black',
  'Blond',
  'Brown',
  'Light brown',
  'Gray',
  'White',
  'Unnatural',
];

export const eyeColors = [
  'Black',
  'Brown',
  'Blue',
  'Green',
  'Gray',
  'Hazel',
  'Mixed',
];

export const formOneStepNames = [
  'Personal',
  'CitizenShip',
  'Address',
  'Appearance',
  'Contact',
];

export const formTwoStepName = [
  'Employment & Weapons',
  'Application Type',
  'Files',
  'Signature',
];

export const employmentStatus = ['Employed', 'Unemployed', 'Retired'];

export const defaultPermitState = {
  application: {
    dob: {
      birthDate: '',
      birthCity: '',
      birthCountry: '',
      birthState: '',
    },
    aliases: [],
    applicationType: '',
    citizenship: { citizen: true, militaryStatus: '' },
    contact: {
      cellPhoneNumber: '',
      faxPhoneNumber: '',
      primaryPhoneNumber: '',
      textMessageUpdates: false,
      workPhoneNumber: '',
    },
    currentAddress: {
      addressLine1: '',
      addressLine2: '',
      city: '',
      country: '',
      county: '',
      state: '',
      zip: '',
    },
    differentMailing: false,
    differentSpouseAddress: false,
    employment: '',
    history: [],
    idInfo: {
      idNumber: '',
      issuingState: '',
    },
    immigrantInformation: {
      countryOfCitizenship: '',
      countryOfBirth: '',
      immigrantAlien: false,
      nonImmigrantAlien: false,
    },
    isComplete: false,
    license: {
      permitNumber: '',
      issuingCounty: '',
      expirationDate: '',
    },
    mailingAddress: {
      addressLine1: '',
      addressLine2: '',
      city: '',
      country: '',
      county: '',
      state: '',
      zip: '',
    },
    personalInfo: {
      lastName: '',
      firstName: '',
      middleName: '',
      noMiddleName: false,
      maidenName: '',
      suffix: '',
      ssn: '',
      maritalStatus: '',
    },
    physicalAppearance: {
      eyeColor: '',
      gender: '',
      hairColor: '',
      heightFeet: '',
      heightInch: '',
      physicalDesc: '',
      weight: '',
    },
    previousAddresses: [],
    qualifyingQuestions: {
      questionOne: false,
      questionOneExp: '',
      questionTwo: false,
      questionTwoExp: '',
      questionThree: false,
      questionThreeExp: '',
      questionFour: false,
      questionFourExp: '',
      questionFive: false,
      questionFiveExp: '',
      questionSix: false,
      questionSixExp: '',
      questionSeven: false,
      questionSevenExp: '',
      questionEight: false,
      questionEightExp: '',
      questionNine: false,
      questionNineExp: '',
      questionTen: false,
      questionTenExp: '',
      questionEleven: false,
      questionElevenExp: '',
      questionTwelve: false,
      questionTwelveExp: '',
      questionThirteen: false,
      questionThirteenExp: '',
      questionFourteen: false,
      questionFourteenExp: '',
      questionFifteen: false,
      questionFifteenExp: '',
      questionSixteen: false,
      questionSixteenExp: '',
      questionSeventeen: false,
      questionSeventeenExp: '',
    },
    spouseInformation: {
      lastName: '',
      firstName: '',
      middleName: '',
      maidenName: '',
    },
    spouseAddressInformation: {
      addressLine1: '',
      addressLine2: '',
      city: '',
      country: '',
      county: '',
      state: '',
      zip: '',
    },
    userEmail: '',
    weapons: [],
    workInformation: {
      employerName: '',
      employerAddressLine1: '',
      employerAddressLine2: '',
      employerCity: '',
      employerCountry: 'United States',
      employerPhone: '',
      employerState: '',
      employerZip: '',
    },
  },
  id: '',
};

export const defaultAllPermitsState = {
  id: '',
  application: {
    personalInfo: defaultPermitState.application.personalInfo,
    currentAddress: defaultPermitState.application.currentAddress,
    isComplete: false,
    userEmail: '',
    applicationType: '',
    paymentStatus: '',
    appointmentStatus: '',
  },
};
