<template>
  <v-container class="mb-10">
    <v-sheet class="rounded p-4">
      <v-subheader class="sub-header font-weight-bold mb-2">
        {{ $t('Qualifying Questions') }}
      </v-subheader>
      <v-form class="ml-5">
        <v-row class="ml-5">
          <v-col
            class="text-left"
            cols="5"
            lg="4"
            sm="1"
          >
            {{ $t('QUESTION-ONE') }}
          </v-col>
          <v-col
            cols="3"
            lg="2"
            sm="1"
          >
            <v-radio-group
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionOne
              "
              row
            >
              <v-radio
                :label="$t('true')"
                :value="true"
              />
              <v-radio
                :label="$t('false')"
                :value="false"
              />
            </v-radio-group>
          </v-col>
          <v-col
            cols="6"
            lg="5"
            sm="1"
            v-if="
              applicationStore.completeApplication.qualifyingQuestions
                .questionOne
            "
          >
            <v-textarea
              outlined
              :label="$t('Please explain')"
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionOneExp
              "
            >
            </v-textarea>
          </v-col>
        </v-row>

        <v-row class="ml-5">
          <v-col
            class="text-left"
            cols="5"
            lg="4"
            sm="1"
          >
            {{ $t('QUESTION-TWO') }}
          </v-col>
          <v-col
            cols="3"
            lg="2"
            sm="1"
          >
            <v-radio-group
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionTwo
              "
              row
            >
              <v-radio
                :label="$t('true')"
                :value="true"
              />
              <v-radio
                :label="$t('false')"
                :value="false"
              />
            </v-radio-group>
          </v-col>
          <v-col
            cols="6"
            lg="5"
            sm="1"
            v-if="
              applicationStore.completeApplication.qualifyingQuestions
                .questionTwo
            "
          >
            <v-textarea
              outlined
              :label="$t('Please explain')"
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionTwoExp
              "
            >
            </v-textarea>
          </v-col>
        </v-row>

        <v-row class="ml-5">
          <v-col
            class="text-left"
            cols="5"
            lg="4"
            sm="1"
          >
            {{ $t('QUESTION-THREE') }}
          </v-col>
          <v-col
            cols="3"
            lg="2"
            sm="1"
          >
            <v-radio-group
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionThree
              "
              row
            >
              <v-radio
                :label="$t('true')"
                :value="true"
              />
              <v-radio
                :label="$t('false')"
                :value="false"
              />
            </v-radio-group>
          </v-col>
          <v-col
            cols="6"
            lg="5"
            sm="1"
            v-if="
              applicationStore.completeApplication.qualifyingQuestions
                .questionThree
            "
          >
            <v-textarea
              outlined
              :label="$t('Please explain')"
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionThreeExp
              "
            >
            </v-textarea>
          </v-col>
        </v-row>

        <v-row class="ml-5">
          <v-col
            class="text-left"
            cols="5"
            lg="4"
            sm="1"
          >
            {{ $t('QUESTION-FOUR') }}
          </v-col>
          <v-col
            cols="3"
            lg="2"
            sm="1"
          >
            <v-radio-group
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionFour
              "
              row
            >
              <v-radio
                :label="$t('true')"
                :value="true"
              />
              <v-radio
                :label="$t('false')"
                :value="false"
              />
            </v-radio-group>
          </v-col>
          <v-col
            cols="6"
            lg="5"
            sm="1"
            v-if="
              applicationStore.completeApplication.qualifyingQuestions
                .questionFour
            "
          >
            <v-textarea
              outlined
              :label="$t('Please explain')"
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionFourExp
              "
            >
            </v-textarea>
          </v-col>
        </v-row>
        <v-row class="ml-5">
          <v-col
            class="text-left"
            cols="5"
            lg="4"
            sm="1"
          >
            {{ $t('QUESTION-FIVE') }}
          </v-col>
          <v-col
            cols="3"
            lg="2"
            sm="1"
          >
            <v-radio-group
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionFive
              "
              row
            >
              <v-radio
                :label="$t('true')"
                :value="true"
              />
              <v-radio
                :label="$t('false')"
                :value="false"
              />
            </v-radio-group>
          </v-col>
          <v-col
            cols="6"
            lg="5"
            sm="1"
            v-if="
              applicationStore.completeApplication.qualifyingQuestions
                .questionFive
            "
          >
            <v-textarea
              outlined
              :label="$t('Please explain')"
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionFiveExp
              "
            >
            </v-textarea>
          </v-col>
        </v-row>

        <v-row class="ml-5">
          <v-col
            class="text-left"
            cols="5"
            lg="4"
            sm="1"
          >
            {{ $t('QUESTION-SIX') }}
          </v-col>
          <v-col
            cols="3"
            lg="2"
            sm="1"
          >
            <v-radio-group
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionSix
              "
              row
            >
              <v-radio
                :label="$t('true')"
                :value="true"
              />
              <v-radio
                :label="$t('false')"
                :value="false"
              />
            </v-radio-group>
          </v-col>
          <v-col
            cols="6"
            lg="5"
            sm="1"
            v-if="
              applicationStore.completeApplication.qualifyingQuestions
                .questionSix
            "
          >
            <v-textarea
              outlined
              :label="$t('Please explain')"
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionSixExp
              "
            >
            </v-textarea>
          </v-col>
        </v-row>
        <v-row class="ml-5">
          <v-col
            class="text-left"
            cols="5"
            lg="4"
            sm="1"
          >
            {{ $t('QUESTION-SEVEN') }}
          </v-col>
          <v-col
            cols="3"
            lg="2"
            sm="1"
          >
            <v-radio-group
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionSeven
              "
              row
            >
              <v-radio
                :label="$t('true')"
                :value="true"
              />
              <v-radio
                :label="$t('false')"
                :value="false"
              />
            </v-radio-group>
          </v-col>
          <v-col
            cols="6"
            lg="5"
            sm="1"
            v-if="
              applicationStore.completeApplication.qualifyingQuestions
                .questionSeven
            "
          >
            <v-textarea
              outlined
              :label="$t('Please explain')"
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionSevenExp
              "
            >
            </v-textarea>
          </v-col>
        </v-row>

        <v-row class="ml-5">
          <v-col
            class="text-left"
            cols="5"
            lg="4"
            sm="1"
          >
            {{ $t('QUESTION-EIGHT') }}
          </v-col>
          <v-col
            cols="3"
            lg="2"
            sm="1"
          >
            <v-radio-group
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionEight
              "
              row
            >
              <v-radio
                :label="$t('true')"
                :value="true"
              />
              <v-radio
                :label="$t('false')"
                :value="false"
              />
            </v-radio-group>
          </v-col>
          <v-col
            cols="6"
            lg="5"
            sm="1"
            v-if="
              applicationStore.completeApplication.qualifyingQuestions
                .questionEight
            "
          >
            <v-textarea
              outlined
              :label="$t('Please explain')"
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionEightExp
              "
            >
            </v-textarea>
          </v-col>
        </v-row>

        <v-row class="ml-5">
          <v-col
            class="text-left"
            cols="5"
            lg="4"
            sm="1"
          >
            {{ $t('QUESTION-NINE') }}
          </v-col>
          <v-col
            cols="3"
            lg="2"
            sm="1"
          >
            <v-radio-group
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionNine
              "
              row
            >
              <v-radio
                :label="$t('true')"
                :value="true"
              />
              <v-radio
                :label="$t('false')"
                :value="false"
              />
            </v-radio-group>
          </v-col>
          <v-col
            cols="6"
            lg="5"
            sm="1"
            v-if="
              applicationStore.completeApplication.qualifyingQuestions
                .questionNine
            "
          >
            <v-textarea
              outlined
              :label="$t('Please explain')"
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionNineExp
              "
            >
            </v-textarea>
          </v-col>
        </v-row>

        <v-row class="ml-5">
          <v-col
            class="text-left"
            cols="5"
            lg="4"
            sm="1"
          >
            {{ $t('QUESTION-TEN') }}
          </v-col>
          <v-col
            cols="3"
            lg="2"
            sm="1"
          >
            <v-radio-group
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionTen
              "
              row
            >
              <v-radio
                :label="$t('true')"
                :value="true"
              />
              <v-radio
                :label="$t('false')"
                :value="false"
              />
            </v-radio-group>
          </v-col>
          <v-col
            cols="6"
            lg="5"
            sm="1"
            v-if="
              applicationStore.completeApplication.qualifyingQuestions
                .questionTen
            "
          >
            <v-textarea
              outlined
              :label="$t('Please explain')"
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionTenExp
              "
            >
            </v-textarea>
          </v-col>
        </v-row>

        <v-row class="ml-5">
          <v-col
            class="text-left"
            cols="5"
            lg="4"
            sm="1"
          >
            {{ $t('QUESTION-ELEVEN') }}
          </v-col>
          <v-col
            cols="3"
            lg="2"
            sm="1"
          >
            <v-radio-group
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionEleven
              "
              row
            >
              <v-radio
                :label="$t('true')"
                :value="true"
              />
              <v-radio
                :label="$t('false')"
                :value="false"
              />
            </v-radio-group>
          </v-col>
          <v-col
            cols="6"
            lg="5"
            sm="1"
            v-if="
              applicationStore.completeApplication.qualifyingQuestions
                .questionEleven
            "
          >
            <v-textarea
              outlined
              :label="$t('Please explain')"
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionElevenExp
              "
            >
            </v-textarea>
          </v-col>
        </v-row>

        <v-row class="ml-5">
          <v-col
            class="text-left"
            cols="5"
            lg="4"
            sm="1"
          >
            {{ $t('QUESTION-TWELVE') }}
          </v-col>
          <v-col
            cols="3"
            lg="2"
            sm="1"
          >
            <v-radio-group
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionTwelve
              "
              row
            >
              <v-radio
                :label="$t('true')"
                :value="true"
              />
              <v-radio
                :label="$t('false')"
                :value="false"
              />
            </v-radio-group>
          </v-col>
          <v-col
            cols="6"
            lg="5"
            sm="1"
            v-if="
              applicationStore.completeApplication.qualifyingQuestions
                .questionTwelve
            "
          >
            <v-textarea
              outlined
              :label="$t('Please explain')"
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionTwelveExp
              "
            >
            </v-textarea>
          </v-col>
        </v-row>

        <v-row class="ml-5">
          <v-col
            class="text-left"
            cols="5"
            lg="4"
            sm="1"
          >
            {{ $t('QUESTION-THIRTEEN') }}
          </v-col>
          <v-col
            cols="3"
            lg="2"
            sm="1"
          >
            <v-radio-group
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionThirteen
              "
              row
            >
              <v-radio
                :label="$t('true')"
                :value="true"
              />
              <v-radio
                :label="$t('false')"
                :value="false"
              />
            </v-radio-group>
          </v-col>
          <v-col
            cols="6"
            lg="5"
            sm="1"
            v-if="
              applicationStore.completeApplication.qualifyingQuestions
                .questionThirteen
            "
          >
            <v-textarea
              outlined
              :label="$t('Please explain')"
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionThirteenExp
              "
            >
            </v-textarea>
          </v-col>
        </v-row>

        <v-row class="ml-5">
          <v-col
            class="text-left"
            cols="5"
            lg="4"
            sm="1"
          >
            {{ $t('QUESTION-FOURTEEN') }}
          </v-col>
          <v-col
            cols="3"
            lg="2"
            sm="1"
          >
            <v-radio-group
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionFourteen
              "
              row
            >
              <v-radio
                :label="$t('true')"
                :value="true"
              />
              <v-radio
                :label="$t('false')"
                :value="false"
              />
            </v-radio-group>
          </v-col>
          <v-col
            cols="6"
            lg="5"
            sm="1"
            v-if="
              applicationStore.completeApplication.qualifyingQuestions
                .questionFourteen
            "
          >
            <v-textarea
              outlined
              :label="$t('Please explain')"
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionFourteenExp
              "
            >
            </v-textarea>
          </v-col>
        </v-row>

        <v-row class="ml-5">
          <v-col
            class="text-left"
            cols="5"
            lg="4"
            sm="1"
          >
            {{ $t('QUESTION-FIFTEEN') }}
          </v-col>
          <v-col
            cols="3"
            lg="2"
            sm="1"
          >
            <v-radio-group
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionFifteen
              "
              row
            >
              <v-radio
                :label="$t('true')"
                :value="true"
              />
              <v-radio
                :label="$t('false')"
                :value="false"
              />
            </v-radio-group>
          </v-col>
          <v-col
            cols="6"
            lg="5"
            sm="1"
            v-if="
              applicationStore.completeApplication.qualifyingQuestions
                .questionFifteen
            "
          >
            <v-textarea
              outlined
              :label="$t('Please explain')"
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionFifteenExp
              "
            >
            </v-textarea>
          </v-col>
        </v-row>

        <v-row class="ml-5">
          <v-col
            class="text-left"
            cols="5"
            lg="4"
            sm="1"
          >
            {{ $t('QUESTION-SIXTEEN') }}
          </v-col>
          <v-col
            cols="3"
            lg="2"
            sm="1"
          >
            <v-radio-group
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionSixteen
              "
              row
            >
              <v-radio
                :label="$t('true')"
                :value="true"
              />
              <v-radio
                :label="$t('false')"
                :value="false"
              />
            </v-radio-group>
          </v-col>
          <v-col
            cols="6"
            lg="5"
            sm="1"
            v-if="
              applicationStore.completeApplication.qualifyingQuestions
                .questionSixteen
            "
          >
            <v-textarea
              outlined
              :label="$t('Please explain')"
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionSixteenExp
              "
            >
            </v-textarea>
          </v-col>
        </v-row>

        <v-row class="ml-5">
          <v-col
            class="text-left"
            cols="5"
            lg="4"
            sm="1"
          >
            {{ $t('QUESTION-SEVENTEEN') }}
          </v-col>
          <v-col
            cols="3"
            lg="2"
            sm="1"
          >
            <v-radio-group
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionSeventeen
              "
              row
            >
              <v-radio
                :label="$t('true')"
                :value="true"
              />
              <v-radio
                :label="$t('false')"
                :value="false"
              />
            </v-radio-group>
          </v-col>
          <v-col
            cols="6"
            lg="5"
            sm="1"
            v-if="
              applicationStore.completeApplication.qualifyingQuestions
                .questionSeventeen
            "
          >
            <v-textarea
              outlined
              :label="$t('Please explain')"
              v-model="
                applicationStore.completeApplication.qualifyingQuestions
                  .questionSeventeenExp
              "
            >
            </v-textarea>
          </v-col>
        </v-row>
      </v-form>
      <FormButtonContainer
        :valid="true"
        @submit="handleSubmit"
        @save="handleSave"
      />
    </v-sheet>
  </v-container>
</template>

<script setup lang="ts">
import FormButtonContainer from '@core-public/components/containers/FormButtonContainer.vue';
import { useCompleteApplicationStore } from '@core-public/stores/completeApplication';
import { useRouter } from 'vue-router/composables';

const applicationStore = useCompleteApplicationStore();
const router = useRouter();

function handleSubmit() {
  router.push('/finalize');
}

function handleSave() {}
</script>

<style lang="scss" scoped></style>
