namespace CCW.Application.Entities;

public class QualifyingQuestions
{
    public bool? QuestionOne { get; set; }
    public string QuestionOneAgency { get; set; }
    public string QuestionOneAgencyTemp { get; set; }
    public string QuestionOneIssueDate { get; set; }
    public string QuestionOneIssueDateTemp { get; set; }
    public string QuestionOneNumber { get; set; }
    public string QuestionOneNumberTemp { get; set; }
    public bool? QuestionTwo { get; set; }
    public string QuestionTwoExp { get; set; }
    public string QuestionTwoTempExplanation { get; set; }
    public bool? QuestionThree { get; set; }
    public string QuestionThreeExp { get; set; }
    public string QuestionThreeTempExplanation { get; set; }
    public bool? QuestionFour { get; set; }
    public string QuestionFourExp { get; set; }
    public string QuestionFourTempExplanation { get; set; }
    public bool? QuestionFive { get; set; }
    public string QuestionFiveExp { get; set; }
    public string QuestionFiveTempExplanation { get; set; }
    public bool? QuestionSix { get; set; }
    public string QuestionSixExp { get; set; }
    public string QuestionSixTempExplanation { get; set; }
    public bool? QuestionSeven { get; set; }
    public string QuestionSevenExp { get; set; }
    public string QuestionSevenTempExplanation { get; set; }
    public bool? QuestionEight { get; set; }
    public string QuestionEightExp { get; set; }
    public string QuestionEightTempExplanation { get; set; }
    public bool? QuestionNine { get; set; }
    public string QuestionNineExp { get; set; }
    public string QuestionNineTempExplanation { get; set; }
    public bool? QuestionTen { get; set; }
    public string QuestionTenExp { get; set; }
    public string QuestionTenTempExplanation { get; set; }
    public bool? QuestionEleven { get; set; }
    public string QuestionElevenExp { get; set; }
    public string QuestionElevenTempExplanation { get; set; }
    public bool? QuestionTwelve { get; set; }
    public string QuestionTwelveExp { get; set; }
    public string QuestionTwelveTempExplanation { get; set; }
    public bool? QuestionThirteen { get; set; }
    public string QuestionThirteenExp { get; set; }
    public string QuestionThirteenTempExplanation { get; set; }
    public bool? QuestionFourteen { get; set; }
    public string QuestionFourteenExp { get; set; }
    public string QuestionFourteenTempExplanation { get; set; }
    public bool? QuestionFifteen { get; set; }
    public string QuestionFifteenExp { get; set; }
    public string QuestionFifteenTempExplanation { get; set; }
    public bool? QuestionSixteen { get; set; }
    public string QuestionSixteenExp { get; set; }
    public string QuestionSixteenTempExplanation { get; set; }
    public bool? QuestionSeventeen { get; set; }
    public string QuestionSeventeenExp { get; set; }
    public string QuestionSeventeenTempExplanation { get; set; }
}
